-- 상세 관심사 추가(2026-10-10): 백엔드 Spring·FastAPI·Java·Kotlin·Python·AWS·Azure·Google Cloud, 프론트엔드 Next.js·Vue·TypeScript, AI 파인튜닝.
-- packages/core/src/topics/dictionary.ts와 같다. 이름·별칭이 바뀐 토픽은 벡터를 다시 만든다(embedding = null).
insert into public.topics (id, name, aliases, popularity)
select id, name, aliases, popularity from (values
  ('backend', '백엔드', array['서버', '서버 개발', 'API', '인프라', '클라우드', 'DevOps']::text[], 1),
  ('frontend', '프론트엔드', array['웹 개발', '자바스크립트', 'JavaScript', 'UI 개발']::text[], 2),
  ('ai', 'AI', array['인공지능', '생성형 AI', '머신러닝', 'ChatGPT', 'Gemini', 'Claude']::text[], 3),
  ('realestate', '부동산', array['아파트', '집값', '주택', '분양', '부동산 시장']::text[], 4),
  ('stock', '주식', array['증시', '코스피', '코스닥', '나스닥', '주식 투자', '종목']::text[], 5),
  ('spring', 'Spring', array['스프링', 'Spring Boot', '스프링 부트', 'Spring Framework']::text[], 15),
  ('fastapi', 'FastAPI', array['패스트API']::text[], 16),
  ('java', 'Java', array['자바', 'JDK', 'OpenJDK', 'JVM']::text[], 17),
  ('kotlin', 'Kotlin', array['코틀린']::text[], 18),
  ('python', 'Python', array['파이썬', 'CPython', 'PyPI']::text[], 19),
  ('aws', 'AWS', array['아마존 웹 서비스', 'Amazon Web Services', 'EC2', 'S3', 'Lambda']::text[], 20),
  ('azure', 'Azure', array['애저', 'Microsoft Azure']::text[], 21),
  ('gcp', 'Google Cloud', array['GCP', '구글 클라우드', 'BigQuery', 'Cloud Run']::text[], 22),
  ('backend-perf', '백엔드 성능', array['성능 튜닝', '레이턴시', '서버 성능', '캐시', '트래픽']::text[], 23),
  ('database', '데이터베이스', array['DB', 'SQL']::text[], 24),
  ('postgres', 'PostgreSQL', array['포스트그레스', 'postgres']::text[], 25),
  ('kubernetes', '쿠버네티스', array['k8s', 'kubernetes', '컨테이너', '도커']::text[], 26),
  ('observability', '관측성', array['모니터링', '트레이싱', 'observability', '로그']::text[], 27),
  ('security', '보안', array['공급망 보안', '취약점', '해킹']::text[], 28),
  ('data-eng', '데이터 엔지니어링', array['데이터 파이프라인', 'ETL']::text[], 29),
  ('react', 'React', array['리액트', '서버 컴포넌트', 'React Native']::text[], 30),
  ('nextjs', 'Next.js', array['넥스트', 'App Router', 'Vercel']::text[], 31),
  ('vue', 'Vue', array['뷰', 'Vue.js', 'Nuxt']::text[], 32),
  ('typescript', 'TypeScript', array['타입스크립트']::text[], 33),
  ('web-perf', '웹 성능', array['Core Web Vitals', '로딩 속도', '프론트엔드 성능', '렌더링']::text[], 34),
  ('design-system', '디자인 시스템', array['디자인 토큰', '컴포넌트 라이브러리', 'UI 디자인', '피그마']::text[], 35),
  ('mobile-app', '모바일 앱', array['iOS', 'Android', '앱 성능', '안드로이드']::text[], 36),
  ('llm-dev', 'LLM', array['LLM 개발', 'LLM API', '언어 모델', '거대 언어 모델', '오픈소스 모델']::text[], 37),
  ('rag', 'RAG', array['검색 증강', '벡터 검색', '벡터 DB']::text[], 38),
  ('fine-tuning', '파인튜닝', array['fine-tuning', '미세 조정', 'LoRA', '학습 데이터']::text[], 39),
  ('llm-agent', 'LLM 에이전트', array['에이전트', 'agent', 'AI 에이전트', '멀티 에이전트']::text[], 40),
  ('prompt', '프롬프트 설계', array['프롬프트 엔지니어링', 'prompt']::text[], 41),
  ('ai-tools', 'AI 도구', array['AI 툴', '코딩 어시스턴트', 'AI 코딩', '코파일럿']::text[], 42),
  ('speech-ai', '음성 AI', array['TTS', 'STT', '음성 합성']::text[], 43),
  ('re-subscription', '청약·분양', array['청약', '분양가', '청약 경쟁률', '특별공급']::text[], 44),
  ('re-policy', '부동산 정책·세금', array['부동산 대책', '대출 규제', 'DSR', '종부세', '양도세', '취득세']::text[], 45),
  ('re-rent', '전월세', array['전세', '월세', '전세 사기', '임대차']::text[], 46),
  ('re-redevelop', '재건축·재개발', array['재건축', '재개발', '정비사업', '리모델링']::text[], 47),
  ('stock-kr', '국내 주식', array['코스피', '코스닥', '국내 증시', '삼성전자']::text[], 48),
  ('stock-us', '미국 주식', array['나스닥', 'S&P500', '뉴욕 증시', '미국 증시', '엔비디아']::text[], 49),
  ('etf', 'ETF·연금 투자', array['ETF', '연금저축', 'IRP', 'ISA', '배당']::text[], 50),
  ('ipo', '공모주', array['IPO', '상장', '수요예측']::text[], 51),
  ('macro', '금리·환율', array['기준금리', '환율', '금리', '연준', 'FOMC', '물가']::text[], 52)
) as v(id, name, aliases, popularity)
on conflict (id) do update set name = excluded.name, aliases = excluded.aliases, popularity = excluded.popularity, embedding = null;

update public.topics t set parent = v.parent from (values
  ('spring', 'backend'),
  ('fastapi', 'backend'),
  ('java', 'backend'),
  ('kotlin', 'backend'),
  ('python', 'backend'),
  ('aws', 'backend'),
  ('azure', 'backend'),
  ('gcp', 'backend'),
  ('backend-perf', 'backend'),
  ('database', 'backend'),
  ('postgres', 'backend'),
  ('kubernetes', 'backend'),
  ('observability', 'backend'),
  ('security', 'backend'),
  ('data-eng', 'backend'),
  ('react', 'frontend'),
  ('nextjs', 'frontend'),
  ('vue', 'frontend'),
  ('typescript', 'frontend'),
  ('web-perf', 'frontend'),
  ('design-system', 'frontend'),
  ('mobile-app', 'frontend'),
  ('llm-dev', 'ai'),
  ('rag', 'ai'),
  ('fine-tuning', 'ai'),
  ('llm-agent', 'ai'),
  ('prompt', 'ai'),
  ('ai-tools', 'ai'),
  ('speech-ai', 'ai'),
  ('re-subscription', 'realestate'),
  ('re-policy', 'realestate'),
  ('re-rent', 'realestate'),
  ('re-redevelop', 'realestate'),
  ('stock-kr', 'stock'),
  ('stock-us', 'stock'),
  ('etf', 'stock'),
  ('ipo', 'stock'),
  ('macro', 'stock')
) as v(id, parent) where t.id = v.id;
